name: Extract Asana Task Assignee
description: Returns the Asana task assignee, if task is assigned
inputs:
  access-token:
    description: "Asana access token"
    required: true
    type: string
  task-id:
    description: "Asana task ID"
    required: true
    type: string
outputs:
  assignee-id:
    description: "Assignee ID"
    value: ${{ steps.extract-assignee-id.outputs.assignee-id }}
runs:
  using: "composite"
  steps:
    - id: extract-assignee-id
      run: |
        assignee_id=$(curl -s "https://app.asana.com/api/1.0/tasks/${task_id}?opt_fields=assignee" \
          -H "Authorization: Bearer ${{ inputs.access-token }}" \
          | jq -r '.data.assignee.gid')
      shell: bash
