name: PIR E2E Tests Scheduled and release branches trigger

on:
  schedule:
     - cron: '0 3 * * 1-5' # 3AM UTC offsetted to legacy to avoid action-junit-report@v4 bug
  pull_request:
    branches:
      - hotfix/*
      - release/*

jobs:
  call-sub-workflow:
    uses: ./.github/workflows/pir_end_to_end_tests.yml
    secrets: inherit
