name: PIR E2E Tests files changed trigger

on:
  pull_request:
    paths:
      - 'LocalPackages/DataBrokerProtection/**'

jobs:
  call-sub-workflow:
    uses: ./.github/workflows/pir_end_to_end_tests.yml
    secrets: inherit
