name: Tag and Merge

on:
  workflow_dispatch:
    inputs:
      asana-task-url:
        description: "Asana release task URL"
        required: true
        type: string
      base-branch:
        description: "Base branch name"
        required: false
        type: string
      branch:
        description: "Branch name"
        required: false
        type: string
  workflow_call:
    inputs:
      asana-task-url:
        description: "Asana release task URL"
        required: true
        type: string
      base-branch:
        description: "Base branch name"
        required: false
        type: string
      branch:
        description: "Branch name"
        required: false
        type: string
    secrets:
      ASANA_ACCESS_TOKEN:
        required: true
      GHA_ELEVATED_PERMISSIONS_TOKEN:
        required: true

jobs:
  tag-and-merge:

    name: Tag and Merge

    runs-on: ubuntu-latest

    env:
      asana-task-url: ${{ github.event.inputs.asana-task-url || inputs.asana-task-url }}
      base-branch: ${{ inputs.base-branch || 'main' }}
      branch: ${{ inputs.branch || github.ref_name }}

    steps:

    - name: Check out the code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ inputs.branch || github.ref_name }}

    - name: Get Asana task ID
      id: get-task-id
      if: env.asana-task-url
      uses: ./.github/actions/extract-asana-task-id
      with:
        task-url: ${{ env.asana-task-url }}

    - name: Get Asana task assignee
      id: get-assignee-id
      if: env.asana-task-url
      uses: ./.github/actions/extract-asana-task-assignee
      with:
        access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
        task-id: ${{ steps.get-task-id.outputs.task-id }}

    - name: Create Tag and GitHub Release
      id: create-tag
      uses: ./.github/actions/create-tag-and-github-release
      with:
        prerelease: true
        github-token: ${{ github.token }}

    - name: Merge to base branch
      id: merge
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GHA_ELEVATED_PERMISSIONS_TOKEN }}
        script: |
          github.rest.repos.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: "${{ env.base-branch }}",
            head: "${{ env.branch }}"
          })

    - name: Create Asana task on failed merge
      if: failure()
      env:
        ASSIGNEE_ID: ${{ steps.get-assignee-id.outputs.assignee-id }}
        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
        TASK_NAME: "Merging ${{ env.branch }} to ${{ env.base-branch }} failed"
        TASK_BODY: "The ${{ steps.create-tag.outputs.tag }} release has been successfully tagged and published in GitHub releases,
          but merging to ${{ env.base-branch }} failed. Please resolve conflicts and merge ${{ env.branch }} to ${{ env.base-branch }} manually."
        TASK_ID: ${{ steps.get-task-id.outputs.task-id }}
        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/subtasks" \
          -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
          -H 'content-type: application/json' \
          --write-out '%{http_code}' \
          --output /dev/null \
          -d "{
                \"data\": {
                  \"name\": \"${TASK_NAME}\",
                  \"resource_subtype\": \"default_task\",
                  \"notes\": \"${TASK_BODY}\n\nWorkflow URL: ${WORKFLOW_URL}\",
                  \"assignee\": \"${ASSIGNEE_ID}\"
                }
              }
          ")

        if [ $return_code -ne 201 ]; then
          echo "::error::Failed to create Asana task"
          exit 1
        fi
