name: Tag and Merge

on:
  workflow_dispatch:
    inputs:
      asana-task-url:
        description: "Asana release task URL"
        required: true
        type: string
      base-branch:
        description: "Base branch name"
        required: false
        type: string
      branch:
        description: "Branch name"
        required: false
        type: string
  workflow_call:
    inputs:
      asana-task-url:
        description: "Asana release task URL"
        required: true
        type: string
      base-branch:
        description: "Base branch name"
        required: false
        type: string
      branch:
        description: "Branch name"
        required: false
        type: string
    secrets:
      ASANA_ACCESS_TOKEN:
        required: true
      GHA_ELEVATED_PERMISSIONS_TOKEN:
        required: true

jobs:
  tag-and-merge:

    name: Tag and Merge

    runs-on: macos-13

    env:
      asana-task-url: ${{ github.event.inputs.asana-task-url || inputs.asana-task-url }}
      BASE_BRANCH: ${{ inputs.base-branch || 'main' }}
      BRANCH: ${{ inputs.branch || github.ref_name }}

    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}

    steps:

    - name: Check out the code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ env.BRANCH }}

    - name: Create Tag and GitHub Release
      id: create-tag
      uses: ./.github/actions/create-tag-and-github-release
      with:
        prerelease: true
        github-token: ${{ github.token }}

    - name: Merge to base branch
      id: merge
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GHA_ELEVATED_PERMISSIONS_TOKEN }}
        script: |
          github.rest.repos.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: "${{ env.BASE_BRANCH }}",
            head: "${{ env.BRANCH }}"
          })

    - name: Set common environment variables
      if: always()
      run: |
        echo "TAG=${{ steps.create-tag.outputs.tag }}" >> $GITHUB_ENV
        echo "WORKFLOW_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
        echo "DMG_URL=${{ vars.TEST_DMG_URL_ROOT }}duckduckgo-${{ steps.create-tag.outputs.tag }}.dmg" >> $GITHUB_ENV
        echo "RELEASE_URL=https://github.com/${{ github.repository }}/releases/tag/${{ steps.create-tag.outputs.tag }}" >> $GITHUB_ENV

    - name: Create Asana task on failed merge
      id: create-task-on-failed-merge
      if: failure()
      uses: ./.github/actions/asana-create-action-item
      with:
        access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
        release-task-url: ${{ env.asana-task-url }}
        template-name: merge-failed

    - name: Report failure
      if: failure()
      uses: ./.github/actions/asana-log-message
      env:
        ASSIGNEE_ID: ${{ steps.create-task-on-failed-merge.outputs.assignee-id }}
        TASK_ID: ${{ steps.create-task-on-failed-merge.outputs.new-task-id }}
      with:
        access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
        task-url: ${{ env.asana-task-url }}
        template-name: internal-release-ready-merge-failed

    - name: Report success
      if: success()
      uses: ./.github/actions/asana-log-message
      with:
        access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
        task-url: ${{ env.asana-task-url }}
        template-name: internal-release-ready
