# This is a basic workflow to help you get started with Actions

name: Screen Size Tests

# Controls when the action will run. 
on:
  workflow_dispatch:
jobs:
  screentest:
    name: UI tests
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-15-xlarge]
        include:
          - xcode-version: "16.0"
            runner: macos-15-xlarge
    
    steps:
      - name: Get Display Information with Diagnostics
        run: |
          echo "Retrieving display information with diagnostics..."
          
          # Run the command, capturing output and exit code
          DISPLAY_INFO=$(system_profiler SPDisplaysDataType 2>&1 | tee display_info.txt)
          EXIT_CODE=$?
          
          # Log the output and exit code
          echo "Display Information Output:"
          echo "$DISPLAY_INFO"
          echo "Exit Code: $EXIT_CODE"
          
          # Check if the command failed and provide an alternative message
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "system_profiler command failed or returned no data."
          fi
        continue-on-error: true

      - name: Upload Display Information (Artifact)
        uses: actions/upload-artifact@v3
        with:
          name: display_info
          path: display_info.txt

      - name: change screen resolution
        run: |
          "/Library/Application Support/VMware Tools/vmware-resolutionSet" 1080 2160
          
      - name: new screen resolution
        run: system_profiler SPDisplaysDataType | grep Resolution